### ISSUE TITLE
Downloaded INVADEseq data not work for cellranger

### ISSUE THREAD

**Issue by oyxf** [FredHutch/invadeseq#4]
Dear author,

I encountered a problem when I used the released data from your work.

First, I downloaded the Invadeseq data from the SRA database, and used fastq-dump --split-files to convert the SRR file to fastq format. The final format was the same as the following picture:

[Show Image](https://github.com/FredHutch/invadeseq/assets/10139551/93fa79af-56d5-413a-a75c-eec11ab69f8c)

Second, I tried to analyze the data using cellranger, but the following error appeared:

[Show Image](https://github.com/FredHutch/invadeseq/assets/10139551/c6d02e7d-86b1-40a9-84e6-8fa9e937715c)

Could you please help me check if there was anything wrong with my process? Your help would be greatly appreciated!

Wish you the best in your research.

**Comment by sminot** [comment]
I'd be happy to provide some feedback on the possible causes of the error your encountered. Would you mind providing:

- The .nextflow.log file created by the run;
- The parameters, `nextflow.config`, and launch script that you used to start the run;
- Any other reference files which were used.

**Comment by hanruiw** [comment]
Dear oxyf,

Thank you very much for your interest in our work!

We understand that you encountered an issue while working with the dataset from our paper "_Galeano Nino et al., Effect of the intratumoral microbiota on spatial and cellular heterogeneity in cancer, 2022_". To possibly remedy this, could you please attempt processing the 16s dataset once more using CellRanger version 6.1.1 and manually setting the chemistry to SC5P-PE? This adjustment might help in resolving the issue you are facing.

If you have any follow-up questions, please feel free to open a new issue here: [Galeano Nino Bullman Intratumoral Microbiota 2022 GitHub Repository](https://github.com/FredHutch/Galeano-Nino-Bullman-Intratumoral-Microbiota_2022).

Thank you again for your engagement with our work, and we look forward to assisting you further.

Best regards,
Hanrui
